[package]
name = "git-flow"
version = "0.1.0"
authors = ["Jason Wang <1724555125@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.10"
clap = "2.33.0"
